

export global Styles {
     // Minimum application window dimensions to ensure usable interface
    out property <length> app_vertical_size: 700px;
    out property <length> app_horizontal_size: 800px;

    // Side menu button opacity
    out property <float> button_pressed_state: 0.8;
    out property <float> button_has_over_state: 0.6;
    out property <float> button_selected_state: 1.0;
    out property <float> button_has_focus_state: 0.8;

    out property <length> small_button_width: 80px;
    out property <length> small_button_height: 20px;

}