// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export { AboutPage } from "about_page.slint";
export { TitlesPage, TitleData, GenreItem } from "titles_page.slint";
export { LocationsPage, LocationData } from "locations_page.slint";
export { AuthorsPage, AuthorData } from "authors_page.slint";
export { PublishersPage, PublisherData } from "publishers_page.slint";
export { GenresPage, GenreData } from "genres_page.slint";
//export { ControlsPage } from "controls_page.slint";
//export { EasingsPage } from "easings_page.slint";
//export { ListViewPage } from "list_view_page.slint";
//export { TableViewPage, TableViewPageAdapter } from "table_view_page.slint";
//export { TextEditPage } from "text_edit_page.slint";
