name: Cargo Build & Test

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Install protoc
        run: sudo apt-get install protobuf-compiler-grpc
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build application
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose